version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: wavedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alloma
    ports:
      - "5433:5432"

  wave-backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
